// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package store

import (
	"context"
)

const getOrCreateConversation = `-- name: GetOrCreateConversation :one
INSERT INTO conversations (user_a, user_b)
VALUES (LEAST($1, $2), GREATEST($1, $2))
ON CONFLICT (user_a, user_b) DO UPDATE SET user_a = EXCLUDED.user_a
RETURNING id, user_a, user_b
`

type GetOrCreateConversationParams struct {
	Column1 interface{}
	Column2 interface{}
}

func (q *Queries) GetOrCreateConversation(ctx context.Context, arg GetOrCreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getOrCreateConversation, arg.Column1, arg.Column2)
	var i Conversation
	err := row.Scan(&i.ID, &i.UserA, &i.UserB)
	return i, err
}
