// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDirectMessage = `-- name: CreateDirectMessage :one
WITH conv AS (
    INSERT INTO conversations (user_a, user_b)
    VALUES (least($1::bigint, $3::bigint),
        greatest($1::bigint, $3::bigint))
        ON CONFLICT (user_a, user_b)
        DO UPDATE SET user_a = EXCLUDED.user_a
    RETURNING id
)
INSERT INTO messages (conversation_id, sender_id, body)
    SELECT id, $1, $2 FROM conv
RETURNING id, room_id, conversation_id, sender_id, body, created_at
`

type CreateDirectMessageParams struct {
	SenderID int64
	Body     string
	ToUserID int64
}

func (q *Queries) CreateDirectMessage(ctx context.Context, arg CreateDirectMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createDirectMessage, arg.SenderID, arg.Body, arg.ToUserID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (room_id, conversation_id, sender_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, room_id, conversation_id, sender_id, body, created_at
`

type CreateMessageParams struct {
	RoomID         pgtype.Int8
	ConversationID pgtype.Int8
	SenderID       int64
	Body           string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.RoomID,
		arg.ConversationID,
		arg.SenderID,
		arg.Body,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT id, room_id, conversation_id, sender_id, body, created_at
FROM messages
WHERE conversation_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListMessagesByConversationParams struct {
	ConversationID pgtype.Int8
	Limit          int32
}

func (q *Queries) ListMessagesByConversation(ctx context.Context, arg ListMessagesByConversationParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversation, arg.ConversationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.ConversationID,
			&i.SenderID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByRoom = `-- name: ListMessagesByRoom :many
SELECT m.id, m.room_id, m.conversation_id, m.sender_id, u.username AS sender_username, m.body, m.created_at
FROM messages m
JOIN users u ON u.id = m.sender_id
WHERE m.room_id = $1
ORDER BY m.created_at DESC
LIMIT $2
`

type ListMessagesByRoomParams struct {
	RoomID pgtype.Int8
	Limit  int32
}

type ListMessagesByRoomRow struct {
	ID             int64
	RoomID         pgtype.Int8
	ConversationID pgtype.Int8
	SenderID       int64
	SenderUsername string
	Body           string
	CreatedAt      pgtype.Timestamptz
}

func (q *Queries) ListMessagesByRoom(ctx context.Context, arg ListMessagesByRoomParams) ([]ListMessagesByRoomRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByRoom, arg.RoomID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByRoomRow
	for rows.Next() {
		var i ListMessagesByRoomRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.ConversationID,
			&i.SenderID,
			&i.SenderUsername,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
