// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Conversation struct {
	ID    int64
	UserA int64
	UserB int64
}

type Message struct {
	ID             int64
	RoomID         pgtype.Int8
	ConversationID pgtype.Int8
	SenderID       int64
	Body           string
	CreatedAt      pgtype.Timestamptz
}

type Room struct {
	ID        int64
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
}

type RoomMember struct {
	RoomID   int64
	UserID   int64
	JoinedAt pgtype.Timestamptz
}

type User struct {
	ID        int64
	Email     string
	Password  string
	CreatedAt pgtype.Timestamptz
}
