// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: room_members.sql

package store

import (
	"context"
)

const getRoomsForUser = `-- name: GetRoomsForUser :many
SELECT r.id, r.name, r.slug, r.created_at
FROM rooms r
JOIN room_members rm ON rm.room_id = r.id
WHERE rm.user_id = $1
ORDER BY r.created_at DESC
`

func (q *Queries) GetRoomsForUser(ctx context.Context, userID int64) ([]Room, error) {
	rows, err := q.db.Query(ctx, getRoomsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isMember = `-- name: IsMember :one
SELECT EXISTS (
  SELECT 1 FROM room_members
  WHERE room_id = $1 AND user_id = $2
) AS is_member
`

type IsMemberParams struct {
	RoomID int64
	UserID int64
}

func (q *Queries) IsMember(ctx context.Context, arg IsMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isMember, arg.RoomID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const joinRoom = `-- name: JoinRoom :exec
INSERT INTO room_members (room_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type JoinRoomParams struct {
	RoomID int64
	UserID int64
}

func (q *Queries) JoinRoom(ctx context.Context, arg JoinRoomParams) error {
	_, err := q.db.Exec(ctx, joinRoom, arg.RoomID, arg.UserID)
	return err
}

const leaveRoom = `-- name: LeaveRoom :exec
DELETE FROM room_members
WHERE room_id = $1 AND user_id = $2
`

type LeaveRoomParams struct {
	RoomID int64
	UserID int64
}

func (q *Queries) LeaveRoom(ctx context.Context, arg LeaveRoomParams) error {
	_, err := q.db.Exec(ctx, leaveRoom, arg.RoomID, arg.UserID)
	return err
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT u.id, u.username
FROM room_members rm
JOIN users u ON u.id = rm.user_id
WHERE rm.room_id = $1
ORDER BY rm.joined_at
`

type ListRoomMembersRow struct {
	ID       int64
	Username string
}

func (q *Queries) ListRoomMembers(ctx context.Context, roomID int64) ([]ListRoomMembersRow, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomMembersRow
	for rows.Next() {
		var i ListRoomMembersRow
		if err := rows.Scan(&i.ID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
